/**
 * Created by eng210 on 16.08.2017.
 */

export const GET_PHARAGRAPHS_REQUEST = 'GET_PHARAGRAPHS_REQUEST';
export const GET_PHARAGRAPHS_SUCCESS = 'GET_PHARAGRAPHS_SUCCESS';
export const GET_PHARAGRAPHS_FAIL = 'GET_PHARAGRAPHS_FAIL';
export const GET_ARCTICLE_NAME = 'GET_ARCTICLE_NAME';
